stages:
- test
- build-review
- review
- release

variables:
  INDEX: "index.html"
  REPO: "templates/simple-webpage"
  AUTHPASSWORD: "example" # change to "" (empty string) to disable authentication
  # username is always "review" (without quotes)

include:
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/before-script.yml'

# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/code-quality.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/tidy.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/blc.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/review/build-review.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/review/review.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/review/stop-review.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/dockerify.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/pages.yml'

sast:
  allow_failure: true
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - |
      docker run \
        --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}" \
        --volume "$PWD:/code" \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    reports:
      sast: gl-sast-report.json
