stages:
- build
- test
- build-review
- review
# - quality-security
- cleanup
- release
- deploy

variables:
  URL: "budata.dbogatov.org" # if you include 'website-deploy'
  INDEX: "index.html"
  DIST: "website"
  REPO: "bu/data-lab/website"
  AUTHPASSWORD: ""

include:
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/before-script.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/tidy.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/blc.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/review/build-review.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/review/review.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/review/stop-review.yml'

# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/code-quality.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/sast.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/deps-scan.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/container-scan.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/dast.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/license-check.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/performance.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/release-docker.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/pages.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/trigger-websites-deploy.yml'

build:
  image: dbogatov/docker-images:alpine-extras-latest
  stage: build
  script:
  - echo "Build"
  tags:
  - docker
