stages:
- test
- build-review
- review
- quality-security # TODO
- release

variables:
  INDEX: "index.html"
  REPO: "templates/simple-webpage"
  AUTHPASSWORD: "example" # change to "" (empty string) to disable authentication
  # username is always "review" (without quotes)

include:
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/before-script.yml'

# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/tidy.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/blc.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/review/build-review.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/review/review.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/review/stop-review.yml'

# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/code-quality.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/sast.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/deps-scan.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/container-scan.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/quality-security/dast.yml'

- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/dockerify.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/pages.yml'

license-check:
  stage: quality-security
  image:
    name: "registry.gitlab.com/gitlab-org/security-products/license-management:$CI_SERVER_VERSION_MAJOR-$CI_SERVER_VERSION_MINOR-stable"
    entrypoint: [""]
  stage: test
  allow_failure: true
  script:
    - /run.sh analyze .
  artifacts:
    reports:
      license_management: gl-license-management-report.json
  tags:
    - docker
