stages:
- test
- release

variables:
  INDEX: "index.html"
  REPO: "templates/simple-webpage"

include:
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/tidy.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/blc.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/dockerify.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/simple-website/pages.yml'
